site_name: DataHop Docs
site_url: https://datahop.network
extra:
  homepage: https://datahop.network

repo_url: https://github.com/datahop

nav:
  - Home: index.md
  - DataHop Service: ipfs.md
  - CLI:
      - datahop: datahop.md
      - daemon: datahop_daemon.md
      - add: datahop_add.md
      - doc: datahop_doc.md
      - get: datahop_get.md
      - index: datahop_index.md
      - info: datahop_info.md
      - matrix: datahop_matrix.md
      - remove: datahop_remove.md
      - stop: datahop_stop.md
      - version: datahop_version.md
  - Mobile: mobile.md
  - How To: how_to.md
  - Demo: demo.md
theme:
    name: material
    logo: user/themes/data-hop/images/favicons/yellow/android-chrome-512x512.png
    favicon: user/themes/data-hop/images/favicons/yellow/favicon-32x32.png
extra_css:
  - stylesheets/extra.css
